name: dzod
description: A powerful Dart schema validation library inspired by Zod, providing type-safe validation, parsing, and inference with excellent developer experience.
version: 0.2.0
homepage: https://github.com/nonstopio/flutter_forge/tree/main/packages/dzod
documentation: https://github.com/nonstopio/flutter_forge/tree/main/packages/dzod
repository: https://github.com/nonstopio/flutter_forge/tree/main/packages/dzod
issue_tracker: https://github.com/nonstopio/flutter_forge/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  test: ^1.24.0
  mockito: ^5.4.0

# No flutter-specific assets needed for this package 
