name: flutter_plugin_for_mono_repo_hooks

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  mason: ^0.1.0-dev.59
  mason_logger: ^0.3.1
  cli_core: ^0.0.2-dev.5

dev_dependencies:
  flutter_lints: ^5.0.0
  test: ^1.21.0
