#!/usr/bin/env bash
# Regenerates example/nonstop_example from the current bricks with every module
# enabled. The output is committed: it is the reviewable snapshot of what
# `nonstop create` produces. Never hand-edit it; change the brick and rerun.
#
# Usage (from anywhere): bash packages/nonstop_cli/tool/generate_example.sh
set -euo pipefail

cli="$(cd "$(dirname "$0")/.." && pwd)"
repo="$(cd "$cli/../.." && pwd)"
name=nonstop_example

(cd "$repo" && dart run tools/update_nonstop_cli_bundles.dart)

rm -rf "$cli/example/$name"
cd "$cli"
dart run bin/nonstop.dart create "$name" \
  --defaults --network --auth --firestore --notifications --analytics \
  --crashlytics --feature-flags --developer --dashboard \
  --org io.nonstop \
  --description "Reference project generated by nonstop_cli." \
  --output-directory example
