import 'package:analytics/analytics.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  test('event catalog keeps stable unique names', () {
    final events = [
      AnalyticsEvents.user.authenticatedRedirect,
      AnalyticsEvents.user.profileUpdated,
      AnalyticsEvents.user.preferencesChanged,
      AnalyticsEvents.user.onboardingCompleted,
      AnalyticsEvents.user.accountDeleted,
      AnalyticsEvents.auth.signIn,
      AnalyticsEvents.auth.signUp,
      AnalyticsEvents.auth.signOut,
      AnalyticsEvents.auth.passwordReset,
      AnalyticsEvents.auth.failed,
      AnalyticsEvents.auth.socialLogin,
      AnalyticsEvents.navigation.screenView,
      AnalyticsEvents.navigation.tabSwitched,
      AnalyticsEvents.navigation.backPressed,
      AnalyticsEvents.navigation.deepLinkOpened,
      AnalyticsEvents.feature.used,
      AnalyticsEvents.feature.tutorialStarted,
      AnalyticsEvents.feature.tutorialCompleted,
      AnalyticsEvents.feature.feedbackGiven,
      AnalyticsEvents.feature.buttonPressed,
      AnalyticsEvents.error.appError,
      AnalyticsEvents.error.networkError,
      AnalyticsEvents.error.crash,
      AnalyticsEvents.error.apiError,
      AnalyticsEvents.error.validationError,
      AnalyticsEvents.app.open,
      AnalyticsEvents.app.background,
      AnalyticsEvents.app.foreground,
      AnalyticsEvents.app.updated,
      AnalyticsEvents.app.installed,
      AnalyticsEvents.app.uninstalled,
      AnalyticsEvents.profile.viewed,
      AnalyticsEvents.profile.edited,
      AnalyticsEvents.profile.photoUpdated,
      AnalyticsEvents.profile.settingsChanged,
      AnalyticsEvents.profile.privacyUpdated,
    ];
    expect(events, [
      'user_authenticated_redirect',
      'user_profile_updated',
      'user_preferences_changed',
      'user_onboarding_completed',
      'user_account_deleted',
      'auth_sign_in',
      'auth_sign_up',
      'auth_sign_out',
      'auth_password_reset',
      'auth_failed',
      'auth_social_login',
      'screen_view',
      'navigation_tab_switched',
      'navigation_back_pressed',
      'navigation_deep_link_opened',
      'feature_used',
      'feature_tutorial_started',
      'feature_tutorial_completed',
      'feature_feedback_given',
      'button_pressed',
      'app_error',
      'network_error',
      'app_crash',
      'api_error',
      'validation_error',
      'app_open',
      'app_background',
      'app_foreground',
      'app_updated',
      'app_installed',
      'app_uninstalled',
      'profile_viewed',
      'profile_edited',
      'profile_photo_updated',
      'profile_settings_changed',
      'profile_privacy_updated',
    ]);
    expect(events.toSet(), hasLength(events.length));
  });
}
