include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - packages/nonstop_cli/bricks/**/__brick__/**
    - "**/coverage/**"
    - "**/build/**"
linter:
  rules:
    constant_identifier_names: false
    directives_ordering: true
