name: notifications
description: "Firebase Cloud Messaging, permissions and device-token management for {{name.titleCase()}}."
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ^3.8.0
  flutter: ">=3.29.0"

dependencies:
  shared_preferences: ^2.5.3
  flutter:
    sdk: flutter
  app_badge_plus: ^1.1.2
  device_info_plus: ^11.1.1
  firebase_core: ^3.14.0
  firebase_messaging: ^15.1.6
  json_annotation: ^4.9.0
  core:
    path: ../core
  di:
    path: ../di
{{#network}}  network:
    path: ../network
{{/network}}
dev_dependencies:
  mocktail: ^1.0.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
