name: {{ name.snakeCase() }}_workspace

###############################################################################
# MONOREPO CONFIGURATION
###############################################################################
# Define the packages that make up your monorepo
# Customize these patterns to match your project structure
packages:
  - apps/*
  - features/*
  - packages/*
  - plugins/*

# Optional: Define package categories for better organization
# Useful for targeting specific groups of packages
categories:
  apps:
    - apps/*
  features:
    - packages/*
  packages:
    - packages/*
  plugins:
    - plugins/**

###############################################################################
# SCRIPTS
###############################################################################
scripts:
  clean:flutter:
    description: "Run flutter clean in all Flutter packages"
    run: flutter clean
    exec:
      concurrency: 4
    packageFilters:
      flutter: true

  lint:
    description: "Run all linting and static analysis checks"
    run: melos run analyze && melos run format

  analyze:
    description: "Run Flutter analyzer in all packages"
    run: flutter analyze . --fatal-infos
    exec:
      concurrency: 1
      failFast: true

  format:
    description: "Format code with dart format"
    run: dart format --set-exit-if-changed .
    exec:
      concurrency: 5

  fix:
    description: "Apply Dart automated fixes to all packages"
    run: dart fix --apply
    exec:
      concurrency: 5
    packageFilters:
      dirExists: lib

  fix:dry:
    description: "Show Dart automated fixes without applying them"
    run: dart fix --dry-run
    exec:
      concurrency: 5
    packageFilters:
      dirExists: lib

  generate:
    description: "Generate code for Dart packages using build_runner"
    run: dart run build_runner build --delete-conflicting-outputs
    exec:
      concurrency: 1
    packageFilters:
      dependsOn: build_runner

  test:
    description: "Run all tests (Dart and Flutter)"
    run: melos run test:select --no-select

  test:select:
    description: "Run tests in Flutter packages"
    run: flutter test --coverage
    exec:
      concurrency: 5
      failFast: true
    packageFilters:
      dirExists: test

  coverage:
    description: "Generate combined coverage report"
    run: dart run scripts/combine_coverage.dart

###############################################################################
# IDE CONFIGURATION
###############################################################################
# Optional: Configure IDE integration
ide:
  intellij:
    enabled: true
    moduleNamePrefix: ''