name: zod_bhai_example
description: Example Flutter app demonstrating zod-bhai usage
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  zod_bhai:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true 