import 'dart:io';

import 'package:mason_logger/mason_logger.dart';
import 'package:pubspec_parse/pubspec_parse.dart';

const _cliDirectory = 'packages/nonstop_cli';

void main() async {
  final logger = Logger();
  logger.info('Starting version update process');

  try {
    // Read the pubspec.yaml file
    final pubspecFile = File('$_cliDirectory/pubspec.yaml');
    logger.info('Reading pubspec.yaml');
    final pubspecContent = await pubspecFile.readAsString();
    final pubspec = Pubspec.parse(pubspecContent);

    // Get the current version
    final version = pubspec.version.toString();
    logger.info('Current version: $version');

    // Update the version.dart file
    final versionFile = File('$_cliDirectory/lib/version.dart');
    logger.info('Updating $_cliDirectory/lib/version.dart');
    await versionFile.writeAsString('''
// Generated code. Do not modify.
// It is generated by the release workflow as post-release hook.

const packageVersion = '$version';
''');

// Check if the file is modified
    final isModified =
        await Process.run('git', ['diff', '--quiet', versionFile.path]);
    if (isModified.exitCode == 1) {
      logger.info('version.dart has been modified');
      await Process.run('git', ['add', versionFile.path]);
      logger.info('${versionFile.path} has been staged');
      logger.success(
        'Successfully updated version.dart with '
        'version $version in $_cliDirectory',
      );
      return;
    }
    logger.success('No changes detected');
  } catch (e) {
    logger.err('An error occurred while updating the version $e');
    exit(1);
  }
}
